config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  authenticated :user do
    root "shops#index", as: :authenticated_root
  end

  unauthenticated do 
    root 'foods#splash', as: :unauthenticated_root
  end

  resources :shops, only: %i[index show new create destroy] do
    resources :foods, only: %i[index new create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :foods, through: :cart_foods
end

app/models/cart_food.rb
class CartFood < ApplicationRecord
  belongs_to :cart
  belongs_to :food
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :foods
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :shop
  has_many :carts, through: :cart_foods
  has_many :orders, through: :order
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :carts
    has_many :foods
    has_many :orders, through: :order
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :update_allowed_parameters, if: :devise_controller?

    protected
    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) do |u|
          u.permit(:name, :phone, :city, :email, :password, :password_confirmation)
        end
        devise_parameter_sanitizer.permit(:account_update) do |u|
          u.permit(:name, :phone, :city, :email, :password, :current_password)
        end
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: [:splash]
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def splash
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.includes(:foods).find(params[:id])
    @categories = Category.all
    @foods = @shop.foods
  end
  
  def new
  end

  def create
  end

  def delete
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def sign_out_user
    sign_out(current_user)
    redirect_to authenticated_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/destroy.html.erb
<h1>Foods#destroy</h1>
<p>Find me in app/views/foods/destroy.html.erb</p>

app/views/foods/index.html.erb
<%= render 'shared/navbar'%>
<h1>Foods#index</h1>
<p class="bg-success text-white">Find me in app/views/foods/index.html.erb</p>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<h1>Foods#new</h1>
<p>Find me in app/views/foods/new.html.erb</p>

app/views/foods/splash.html.erb
<section class="splash-section d-flex justify-content-center align-items-center">
    <div class="splash-container d-flex flex-column align-items-end justify-content-between">
        <figure class="logo-container">
            <img src="./assets/foodpanda.png" width="300px">
            <h2 class="text-center text-secondary">Welcome to Food panda</h2>
        </figure>
        <div class="link-container w-100 d-flex justify-content-center">
            <%= link_to 'LOG IN', new_user_session_path, class: 'btn btn-primary text-white me-3'%>
            <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-primary text-white'%>
        </div>
       
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantOrderSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
          <script src="https://kit.fontawesome.com/9e6b5903a6.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  
  </head>

  <body>
    
    <%= yield %>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary  ">
  <div class="container-fluid">
  <% if back%>
        <a class="navbar-brand text-uppercase text-primary bold" href="#"><%= current_user.name %></a>
  <% else %>
        <%= link_to("javascript:history.back()", class: "text-dark") do %>
            <i class="fas fa-angle-left h2 mb-0 " ></i>
        <% end %>
  <% end %>
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon text-white"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">Order</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name%>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Sign up</a></li>
            <li><%= link_to 'Log Out', sign_out_user_path , class: 'dropdown-item' %></li>

          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_noti.html.erb
<div class="noti-container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

app/views/shops/create.html.erb
<h1>Shops#create</h1>
<p>Find me in app/views/shops/create.html.erb</p>

app/views/shops/delete.html.erb
<h1>Shops#delete</h1>
<p>Find me in app/views/shops/delete.html.erb</p>

app/views/shops/index.html.erb
<%= render 'shared/navbar', back: true%>
<h2 class="text-center p-3">Shops</h2>
<% @shops.each do |shop| %>
    <div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
  <%= link_to shop_path(id: shop.id), class:'text-decoration-none' do%>
   <div class="card mx-auto" style="width: 18rem;">
  <img src=<%= shop.image %> class="card-img-top" alt="...">
  <div class="card-body">
    <h2 class="card-text text-uppercase"><%= shop.name %></h2>
    <span class="text-capitalize"><%= shop.city %></span>
  </div>
</div>
<% end %>
  </div>

</div>
<% end %>

app/views/shops/show.html.erb
<%= render 'shared/navbar', back: false%>
<section class="food-section">
    <div class="food-container">
        <header class="food-header d-flex p-4 align-items-center">
            <img src=<%= @shop.image%> alt="header-img" width="70px" class="me-4">
            <h2 class="text-uppercase text-white"><%= @shop.name %></h2>
        </header>

        <div class="title-container p-4">
            <div class="d-flex justify-content-between">
                <h1><i class="fas fa-fire text-danger me-2"></i>Popular</h1>
                <%= form_tag(shop_foods_path(shop_id: @shop.id), method: 'get', remote: true) do %>
                <%= select_tag :category_id, options_from_collection_for_select(@categories, 'id', 'name'), include_blank: 'All Categories', class: 'p-1 text-capitalize' %>
                <%= submit_tag 'Filter', class: 'btn my-btn text-white bg-pink rounded' %>
                <% end %>

            </div>
            <span class="text-secondary">Most order right now.</span>
        </div>

        <div class="food-container row row-cols-2 row-cols-md-4 row-cols-md-6 gy-5 px-4">
        <% @foods.each do |food|%>
            <div class="col food-card">
                    <img src=<%= food.image %> class="card-img-top rounded" alt="...">
                    <div class="card-body d-flex  align-items-center justify-content-between">
                        <h6 class="card-text text-uppercase mb-0 p-2 fw-bold"><%= food.name %></h6>
                        <span class="text-capitalize text-secondary fw-semibold">$<%= food.price %></span>
                    </div>
                    <div class="button container p-0 mt-2 d-flex justify-content-between">
                        <button class=" bg-pink text-white btn my-btn">Add Cart</button>
                        <button type="button" class="btn my-btn text-white bg-pink rounded-circle" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            <i class ="fas fa-info"></i>
                        </button>

                        <%# Model %>
                                            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        <div class="modal-header bg-light-pink text-white">
                            <h1 class="modal-title text-uppercase  fs-5" id="exampleModalLabel"><%= food.name %></h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body p-0">
                           <img src=<%= food.image%> width="100%">
                           <p class="mt-2 text-secondary px-3 py-1"><%= food.description %></p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button class=" bg-pink text-white btn my-btn" type="button">Add Cart</button>
                        </div>
                        </div>
                    </div>
                    </div>
                    </div>
            </div>
           
        <% end %>
        </div>
    </div>
</section>

app/views/users/sign_out_user.html.erb
<h1>Users#sign_out_user</h1>
<p>Find me in app/views/users/sign_out_user.html.erb</p>